name: flutter_wearable_app
description: "Elite Industrial IoT Wearable Safety & Health Dashboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12
  tflite_flutter: 0.11.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  telephony: ^0.2.0
  flutter_secure_storage: ^9.2.2
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/data/
